# Generated by Django 5.1.6 on 2026-02-08 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollutantReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pm25', models.FloatField()),
                ('pm10', models.FloatField()),
                ('no2', models.FloatField()),
                ('so2', models.FloatField()),
                ('co', models.FloatField()),
                ('o3', models.FloatField()),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('zone_type', models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm25', models.FloatField(blank=True, null=True)),
                ('pm10', models.FloatField(blank=True, null=True)),
                ('co', models.FloatField(blank=True, null=True)),
                ('o3', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='policy.station')),
            ],
        ),
    ]
