# Generated by Django 5.1.6 on 2026-02-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_alter_pollutantreading_id_alter_sensorreading_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='zone_type',
        ),
        migrations.AddField(
            model_name='station',
            name='city',
            field=models.CharField(default='Delhi', max_length=100),
        ),
        migrations.AddField(
            model_name='station',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pollutantreading',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='SensorReading',
        ),
    ]
